### ISSUE TITLE
Image sending fails

### ISSUE THREAD

**Issue by yaroslavyaroslav** [ijwfly/chatgpt-tg#14]
The following error appears on an image send in tg.

```
app_1               | 2023-12-09 18:24:50,460 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
app_1               | 2023-12-09 18:25:15,633 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
app_1               | 2023-12-09 18:25:15,722 - asyncio - ERROR - Task exception was never retrieved
app_1               | future: <Task finished name='Task-49' coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=BadRequestError("Error code: 400 - {'error': {'message': 'Invalid image.', 'type': 'invalid_request_error', 'param': None, 'code': None}}")>
app_1               | Traceback (most recent call last):
app_1               |   File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
app_1               |     for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
app_1               |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
app_1               |     return await asyncio.gather(*tasks)
app_1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
app_1               |     response = await handler_obj.handler(*args, **partial_data)
app_1               |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
app_1               |     return await self.message_handlers.notify(update.message)
app_1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
app_1               |     response = await handler_obj.handler(*args, **partial_data)
app_1               |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/src/app/app/bot/batched_input_handler.py", line 55, in handle
app_1               |     await self.handle_batch(messages_batch, user)
app_1               |   File "/usr/src/app/app/bot/batched_input_handler.py", line 73, in handle_batch
app_1               |     await self.process_batch(messages_batch, user)
app_1               |   File "/usr/src/app/app/bot/batched_input_handler.py", line 114, in process_batch
app_1               |     await self.answer_message(message, user, message_processor)
app_1               |   File "/usr/src/app/app/bot/batched_input_handler.py", line 184, in answer_message
app_1               |     await message_processor.process(is_cancelled)
app_1               |   File "/usr/src/app/app/bot/message_processor.py", line 77, in process
app_1               |     await self.handle_gpt_response(
app_1               |   File "/usr/src/app/app/bot/message_processor.py", line 82, in handle_gpt_response
app_1               |     response_dialog_message, message_id = await self.handle_response_generator(response_generator)
app_1               |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/src/app/app/bot/message_processor.py", line 124, in handle_response_generator
app_1               |     async for dialog_message in response_generator:
app_1               |   File "/usr/src/app/app/bot/chatgpt_manager.py", line 19, in send_user_message_sync
app_1               |     dialog_message, completion_usage = await self.chatgpt.send_messages(messages)
app_1               |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/src/app/app/openai_helpers/chatgpt.py", line 110, in send_messages
app_1               |     resp = await OpenAIAsync.instance().chat.completions.create(
app_1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1113, in create
app_1               |     return await self._post(
app_1               |            ^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1480, in post
app_1               |     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
app_1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1275, in request
app_1               |     return await self._request(
app_1               |            ^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1318, in _request
app_1               |     raise self._make_status_error_from_response(err.response) from None
app_1               | openai.BadRequestError: Error code: 400 - {'error': {'message': 'Invalid image.', 'type': 'invalid_request_error', 'param': None, 'code': None}}
app_1               | 2023-12-09 18:26:19,985 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
app_1               | 2023-12-09 18:26:20,072 - asyncio - ERROR - Task exception was never retrieved
app_1               | future: <Task finished name='Task-69' coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=BadRequestError("Error code: 400 - {'error': {'message': 'Invalid image.', 'type': 'invalid_request_error', 'param': None, 'code': None}}")>
app_1               | Traceback (most recent call last):
app_1               |   File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
app_1               |     for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
app_1               |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
app_1               |     return await asyncio.gather(*tasks)
app_1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
app_1               |     response = await handler_obj.handler(*args, **partial_data)
app_1               |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
app_1               |     return await self.message_handlers.notify(update.message)
app_1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
app_1               |     response = await handler_obj.handler(*args, **partial_data)
app_1               |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/src/app/app/bot/batched_input_handler.py", line 55, in handle
app_1               |     await self.handle_batch(messages_batch, user)
app_1               |   File "/usr/src/app/app/bot/batched_input_handler.py", line 73, in handle_batch
app_1               |     await self.process_batch(messages_batch, user)
app_1               |   File "/usr/src/app/app/bot/batched_input_handler.py", line 114, in process_batch
app_1               |     await self.answer_message(message, user, message_processor)
app_1               |   File "/usr/src/app/app/bot/batched_input_handler.py", line 184, in answer_message
app_1               |     await message_processor.process(is_cancelled)
app_1               |   File "/usr/src/app/app/bot/message_processor.py", line 77, in process
app_1               |     await self.handle_gpt_response(
app_1               |   File "/usr/src/app/app/bot/message_processor.py", line 82, in handle_gpt_response
app_1               |     response_dialog_message, message_id = await self.handle_response_generator(response_generator)
app_1               |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/src/app/app/bot/message_processor.py", line 124, in handle_response_generator
app_1               |     async for dialog_message in response_generator:
app_1               |   File "/usr/src/app/app/bot/chatgpt_manager.py", line 19, in send_user_message_sync
app_1               |     dialog_message, completion_usage = await self.chatgpt.send_messages(messages)
app_1               |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/src/app/app/openai_helpers/chatgpt.py", line 110, in send_messages
app_1               |     resp = await OpenAIAsync.instance().chat.completions.create(
app_1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1113, in create
app_1               |     return await self._post(
app_1               |            ^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1480, in post
app_1               |     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
app_1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1275, in request
app_1               |     return await self._request(
app_1               |            ^^^^^^^^^^^^^^^^^^^^
app_1               |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1318, in _request
app_1               |     raise self._make_status_error_from_response(err.response) from None
app_1               | openai.BadRequestError: Error code: 400 - {'error': {'message': 'Invalid image.', 'type': 'invalid_request_error', 'param': None, 'code': None}}```

**Comment by yaroslavyaroslav** [comment]
In addition to that it never comes back to ordinary chat after that error and keeping spamming the following error on each request:

```
openai.BadRequestError: Error code: 400 - {'error': {'message': 'Invalid content type. image_url is only supported by certain models.', 'type': 'invalid_request_error', 'param': 'messages.[9].content.[0].type', 'code': None}}
^CGracefully stopping... (press Ctrl+C again to force)
```

**Comment by ijwfly** [comment]
> `'message': 'Invalid image.'`

Usually, it means that chatgpt cannot access image. `main_image_proxy.py` script is responsible for that mechanism. Did you set up IMAGE_PROXY_URL with your IP and port? You can try to access it from outside and see if it opens.
Also, you can debug your setup by looking chatgpttg.message table in postgres, there will be message with image url. You can check it and try to open it.

This mechanism is hard to set up and I don't have ideas how to easen it.

> In addition to that it never comes back to ordinary chat after that error and keeping spamming the following error on each request:

Yeah, it's because you have image in your current context and current chosen model doesn't support images. I think I should add check and custom error message for this case to make it clearer.

**Comment by yaroslavyaroslav** [comment]
Now I see. Yep, I've ignored those fields completely as I thought those are optional.

After messing quite a bit with the setup I succeeded with it just recently. 

As for my taste those are mostly documentation issues rather than setup complexity itself. I'll try to provide a PR with a few suggestion how to improve the `settings.py` pretty shortly.

Thanks for your work once again.
